### ISSUE TITLE
Tested on Linux

### ISSUE THREAD

**Issue by 641i130** [venashial/Poptropica-Desktop#1]
Just letting you know I've tested the Linux build and it works great! Running on Arch Linux with i3wm. 
 
Heres what you could put for the release:
**Linux**
1. Download the `Poptropica-x.x.x.AppImage`. 
2. Open a terminal in that directory and do `sudo chmod +x Poptropica-x.x.x.AppImage` to give yourself permission to run the binary. 
3. Then run it by doing `./Poptropica-x.x.x.AppImage`.

**Comment by venashial** [comment]
Thanks!
