### ISSUE TITLE
Kid Friendly Poptropica

### ISSUE THREAD

**Issue by joeynigro** [venashial/Poptropica-Desktop#2]
I would like Kid Friendly Poptropica with no movieclip variants which doesn't antagonize Mr. Silva and where Molly Moskins wears pants and where the huntsman doesn't threaten Red's grandma and where Isabella has no blood stains or a cleaver and where Happy Tree Friends Island has no gore and where Mike Teavee and El Mustachio Grande have no guns or ammo and where the Zombie Nerd costume doesn't exist.

**Comment by venashial** [comment]
This only wraps the real Poptropica game.
