### ISSUE TITLE
flash  emulation?

### ISSUE THREAD

**Issue by tigercoding56** [venashial/Poptropica-Desktop#3]
would it be possible to emulate flash using  ligthspark for example and also be able to play old levels ?

**Comment by venashial** [comment]
That would be out of the scope of this project, the goal is just to run Poptropica as-is in a desktop-like app. To play old islands, you should check out [this guide on playing Poptropica with Flashpoint](https://server.idkonpop.com/pop/teleport/oldIslandMap).
